# Generated by Django 6.0 on 2026-01-28 05:19

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0004_invoice_invoice_file_invoice_upload_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchaseorder',
            options={'ordering': ['-order_date', '-created_at']},
        ),
        migrations.AlterModelOptions(
            name='purchaserequest',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameField(
            model_name='purchaserequest',
            old_name='notes',
            new_name='justification',
        ),
        migrations.RemoveField(
            model_name='goodsreceipt',
            name='receipt_date',
        ),
        migrations.RemoveField(
            model_name='goodsreceipt',
            name='receipt_number',
        ),
        migrations.RemoveField(
            model_name='purchaserequest',
            name='request_date',
        ),
        migrations.RemoveField(
            model_name='purchaserequest',
            name='request_number',
        ),
        migrations.RemoveField(
            model_name='purchaserequest',
            name='requested_by',
        ),
        migrations.RemoveField(
            model_name='purchaserequest',
            name='required_by_date',
        ),
        migrations.AddField(
            model_name='goodsreceipt',
            name='delivered_quantity',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='goodsreceipt',
            name='received_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_purchase_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='delay_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='delivery_deadline',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='total_quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='department',
            field=models.CharField(default='General', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='employee',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='employee_purchase_requests', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='item_name',
            field=models.CharField(default='Unknown Item', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='procurement.product'),
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='quantity',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='urgency_level',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=10),
        ),
        migrations.AlterField(
            model_name='goodsreceipt',
            name='condition',
            field=models.CharField(choices=[('good', 'Good Condition'), ('damaged', 'Damaged'), ('partial', 'Partial Delivery'), ('shortage', 'Shortage')], default='good', max_length=20),
        ),
        migrations.AlterField(
            model_name='goodsreceipt',
            name='purchase_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='goods_receipts', to='procurement.purchaseorder'),
        ),
        migrations.AlterField(
            model_name='goodsreceipt',
            name='received_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_goods', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='expected_delivery_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='order_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='purchase_request',
            field=models.ForeignKey(blank=True, help_text='Source purchase request', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_orders', to='procurement.purchaserequest'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('approved', 'Approved'), ('sent', 'Sent to Vendor'), ('in_progress', 'In Progress'), ('received', 'Received'), ('delivered', 'Delivered'), ('delayed', 'Delayed'), ('cancelled', 'Cancelled')], default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders', to='procurement.vendor'),
        ),
        migrations.AlterField(
            model_name='purchaseorderitem',
            name='line_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='purchaserequest',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_purchase_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='purchaserequest',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('completed', 'Completed')], default='pending', max_length=20),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('approval', 'Approval'), ('rejection', 'Rejection'), ('delivery', 'Delivery'), ('general', 'General')], default='general', max_length=20)),
                ('message', models.TextField()),
                ('read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('related_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='procurement.purchaseorder')),
                ('related_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='procurement.purchaserequest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
