# Generated by Django 6.0 on 2026-01-29 20:16

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0006_add_vendordocument_sql'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('approval', 'Approval'), ('rejection', 'Rejection'), ('delivery', 'Delivery'), ('rfq', 'RFQ'), ('quotation', 'Quotation'), ('general', 'General')], default='general', max_length=20),
        ),
        migrations.AlterField(
            model_name='purchaserequest',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('rfq_sent', 'RFQ Sent to Vendor'), ('quotation_received', 'Quotation Received'), ('completed', 'Completed')], default='pending', max_length=20),
        ),
        migrations.CreateModel(
            name='RequestForQuotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rfq_number', models.CharField(max_length=50, unique=True)),
                ('sent_date', models.DateTimeField(auto_now_add=True)),
                ('response_deadline', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('sent', 'Sent to Vendor'), ('received', 'Quotation Received'), ('accepted', 'Quotation Accepted'), ('rejected', 'Quotation Rejected'), ('expired', 'Expired')], default='sent', max_length=20)),
                ('admin_notes', models.TextField(blank=True, help_text='Internal notes from admin')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('purchase_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rfqs', to='procurement.purchaserequest')),
                ('sent_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_rfqs', to=settings.AUTH_USER_MODEL)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rfqs', to='procurement.vendor')),
            ],
            options={
                'verbose_name': 'Request for Quotation',
                'verbose_name_plural': 'Requests for Quotation',
                'ordering': ['-sent_date'],
            },
        ),
        migrations.AddField(
            model_name='notification',
            name='related_rfq',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='procurement.requestforquotation'),
        ),
        migrations.CreateModel(
            name='VendorQuotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quotation_number', models.CharField(max_length=50, unique=True)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('quantity', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('tax_rate', models.DecimalField(decimal_places=2, default=0, help_text='Tax percentage (e.g., 18 for 18%)', max_digits=5)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('shipping_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('estimated_delivery_days', models.IntegerField(help_text='Number of days for delivery', validators=[django.core.validators.MinValueValidator(1)])),
                ('quotation_valid_until', models.DateField(help_text='Date until this quotation is valid')),
                ('payment_terms', models.CharField(default='Net 30', max_length=200)),
                ('warranty_terms', models.TextField(blank=True)),
                ('additional_notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('under_review', 'Under Review'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='draft', max_length=20)),
                ('reviewed_date', models.DateTimeField(blank=True, null=True)),
                ('review_notes', models.TextField(blank=True)),
                ('submitted_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_quotations', to=settings.AUTH_USER_MODEL)),
                ('rfq', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='quotation', to='procurement.requestforquotation')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='vendor_quotation',
            field=models.ForeignKey(blank=True, help_text='Source vendor quotation', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_orders', to='procurement.vendorquotation'),
        ),
    ]
