# Generated by Django 6.0 on 2026-02-04 18:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0008_vendor_approved_at_vendor_approved_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='purchase_request',
            field=models.ForeignKey(blank=True, help_text='Source purchase request', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders', to='procurement.purchaserequest'),
        ),
    ]
