# Generated by Django 6.0 on 2026-02-05 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0012_alter_purchaseorderitem_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorderitem',
            name='product_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
